name: Doxygen Deployment

on:
  push:
    branches: ["main"] # mainブランチにpushされたら実行

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz
        
      - name: Run Doxygen
        run: doxygen doxyfile.txt # Doxyfileがある前提
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _doxy # Doxygenの出力先フォルダを指定

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
